apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: ${project.artifactId}
  name: ${project.artifactId}
spec:
  replicas: 1
  selector:
    app: ${project.artifactId}
  strategy:
    resources:
      limits:
        memory: "256Mi"
      requests:
        memory: "20Mi"
    type: Recreate
  template:
    metadata:
      name: ${project.artifactId}
      labels:
        app: ${project.artifactId}
        syndesis.io/type: datavirtualization
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9779"
    spec:
      containers:
      - name: spring-boot
        env:
        - name: JAVA_APP_DIR
          value: /deployments
        - name: JAVA_OPTIONS
          value: "-Djava.net.preferIPv4Stack=true -Duser.home=/tmp -Djava.net.preferIPv4Addresses=true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPRING_DATASOURCE_SAMPLEDB_USERNAME
          valueFrom:
             secretKeyRef:
               name: postgresql
               key: database-user
        - name: SPRING_DATASOURCE_SAMPLEDB_PASSWORD
          valueFrom:
             secretKeyRef:
               name: postgresql
               key: database-password
        - name: SPRING_DATASOURCE_SAMPLEDB_DATABASENAME
          valueFrom:
             secretKeyRef:
               name: postgresql
               key: database-name                 
        - name: SPRING_DATASOURCE_SAMPLEDB_JDBCURL
          value: jdbc:postgresql://postgresql/$(SPRING_DATASOURCE_SAMPLEDB_DATABASENAME) 
        - name: JAVA_DEBUG
          value: "true"
        - name: AB_JMX_EXPORTER_CONFIG
          value: "prometheus-config.yml"
        - name: TEIID_PG_SECURE_ENABLE
          value: "true"
        - name: TEIID_SSL_KEYSTORE_FILENAME
          value: /var/run/secrets/java.io/keystores/keystore.jks
        - name: TEIID_SSL_KEYSTORE_PASSWORD
          value: changeit
        volumeMounts:
          - name: keystore-volume
            mountPath: /var/run/secrets/java.io/keystores
        image: ${project.artifactId}:${project.version}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: "/actuator/health"
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: "/actuator/health"
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
        ports:
        - containerPort: 35432
          name: pg
        - containerPort: 31000
          name: teiid
        - containerPort: 8080
          name: http
        - containerPort: 9779
          name: prometheus
        - containerPort: 8778
          name: jolokia
        workingDir: /deployments
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1.0"
      initContainers:
      - name: pem-to-keystore
        image: jboss/keycloak-openshift
        env:
          - name: keyfile
            value: /var/run/secrets/openshift.io/services_serving_certs/tls.key
          - name: crtfile
            value: /var/run/secrets/openshift.io/services_serving_certs/tls.crt
          - name: keystore_pkcs12
            value: /var/run/secrets/java.io/keystores/keystore.pkcs12
          - name: keystore_jks
            value: /var/run/secrets/java.io/keystores/keystore.jks
          - name: password
            value: changeit
        command: ['/bin/bash']
        args: ['-c', "openssl pkcs12 -export -inkey $keyfile -in $crtfile -out $keystore_pkcs12 -password pass:$password && keytool -importkeystore -noprompt -srckeystore $keystore_pkcs12 -srcstoretype pkcs12 -destkeystore $keystore_jks -storepass $password -srcstorepass $password"]
        volumeMounts:
          - name: keystore-volume
            mountPath: /var/run/secrets/java.io/keystores
          - name: service-certs
            mountPath: /var/run/secrets/openshift.io/services_serving_certs
      volumes:
      - name: keystore-volume
        emtpyDir: {}
      - name: service-certs
        secret:
          secretName: service-certs
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      -  ${project.artifactId}
      from:
        kind: ImageStreamTag
        name: ${project.artifactId}:${project.version}
    type: ImageChange
  - type: ConfigChange
