apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}-pg-secure
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: service-certs
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
  ports:
  - name: ${project.artifactId}-pg-secure
    port: 35443
    targetPort: 35443
  selector:
    app: ${project.artifactId}
